Fusion Touch Ups + Fusion Verification
Cornell-QCA/anyon-braiding-simulator pull request #56
Opened 2024-06-21 05:17 UTC by Haadi-Khan

Sorry probably should've made this 2 PRs but forgot that I didn't merge the touch ups lol.

First set of 3 commits generalized the topo charge enum & updated the documentation

The most recent commits adds fusion verification given an initial topo charge w/ testing

2024-06-21 05:42 UTC, Haadi-Khan commented
PR can't merge until Simulator code is pushed, ignore for now

2024-06-22 00:36 UTC, rbyrne299 approved these changes

2024-06-22 01:05 UTC, rbyrne299 requested changes
Could you make any necessary updates in main.py to account for the new generalized TopoCharge? Thanks!

2024-06-22 01:06 UTC, Haadi-Khan commented
we're so in sync fr

2024-06-22 01:09 UTC, rbyrne299 approved these changes

2024-06-22 01:10 UTC, merged